### ISSUE TITLE
[high] class initialization process is confusing

### ISSUE THREAD

**Issue by mick-warehime** [mick-warehime/swmp#115]
i'm trying to create a new dynamic object and im confused with all this check_class_initialized business. when do i need to use this fancy initializations? when do i check? what class variables do i need to define - i think this is too complicated and requires the subclasses to know too much about this initing process

what i would prefer is a class that can simply inherit from dynamic object and not care about the initialization optimizations. can we use some sort of lazy initialization for this process that is totally transparent to the subclasses? 

more important - i think we are doing this to prevent reloading the base image over and over but loading this image is already cheap because i cache this in the image loader - we only hit the disk once per image. is there a compelling reason for the complex initialization process?

**Comment by dvirk** [comment]
Here is how to make a subclass of DynamicObject:

If there are no new class variables you need to load before instantiating the object, all you need to do is, in the __init__, call self._check_class_initialized(). This will ensure that a Timer object is available (because the new class is a DynamicObject) in self._timer, and a Groups object is available in self._groups (because DynamicObject is a GameObject). For an example, see the MuzzleFlash class in weapons.py (PR #116).  Alternatively, if you don't need access to time information, just make a GameObject class using the same steps.

I agree that GameObject is a little overcomplicated at the moment. Realistically we can probably remove the hit_rect attribute, for example.

**Comment by dvirk** [comment]
@mick-warehime 
Regarding the initialization process:

At least in terms of code simplicity, it doesn't make sense to me that we should have to instantiate each GameObject with it's own image. That's why I prefer using class variables. The class initializations only needs to be done in one place (in the DungeonController), so it should not be difficult to deal with.

**Comment by mick-warehime** [comment]
we can use a class variable - but we should also use lazy initialization. callers shouldnt be required to know the initialization process. the image caching is already done in images.py

**Comment by dvirk** [comment]
I'll change the image initialization part so that the class variable stored is just the filename. I'll try to simplify GameObject by merging hit_rect with rect and removing and base_image, and just make image a required property of any subclass.
