### ISSUE TITLE
[high] define what 'done' means for first phase

### ISSUE THREAD

**Issue by mick-warehime** [mick-warehime/swmp#82]
phase 1 - implement a 'game' 
phase 2 - refactor
phase 3 - refine mechanics/skills/story

what does 1 consist of? minimum set of features and functionalities

**Comment by dvirk** [comment]
I think we need to be at a point where it's possible to build all the components we want in the game. So it should be easy to generate a new Weapon type or Mod, and it should be easy to generate a new Quest line and connect it to a set of Quests. Ideally we would have some menus and a way to customize the initial character, as well as Save/Load functionality.

I think we shouldn't worry too much about AI for the monsters quite yet, since that can take a long time to implement. Also, we should ideally be doing phase 2 at the same time as phase 1, since adding a new feature will likely first require us to refactor relevant classes to make them more usable.
